---
title: "Weight of Fish"
author: "Amy Estrada"
date: "Spring 2021"
output:
  html_document:
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
---


```{r include=FALSE,echo=FALSE}
require(tigerstats)
require(tidyverse)
```
```{r}
Fishdata=read.csv(file="Fish.csv")
```


# Introduction

<!--In this section you explain what you are trying to show.  Where did the data come from?  What is the research or other question you are trying to answer?!-->

## Build the best regression model you can that predicts the weight of perch
## Using only two predictor variables  

# Perch
## Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

```{r}
Perchdata=filter(Fishdata,Species=="Perch")
Perchdata = subset(Perchdata, select= -Species)
```

## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight~.,
               data = Perchdata,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```
  
##Which is best??  

```{r}
which.max(summary.out$adjr2)
```
```{r}
summary.out$which[3,]
```

```{r}
best.model <- lm(Weight~Height+Width,data=Perchdata)
fullup <- lm(Weight~.,data=Perchdata)
summary(best.model)
```

```{r}
anova(fullup,best.model)
```

# Bream
## Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

```{r}
Breamdata=filter(Fishdata,Species=="Bream")
Breamdata = subset(Breamdata, select= -Species)
```

## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight~.,
               data = Breamdata,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```
  
##Which is best??  

```{r}
which.max(summary.out$adjr2)
```
```{r}
summary.out$which[3,]
```

```{r}
best.model2 <- lm(Weight~Height+Width,data=Breamdata)
fullup <- lm(Weight~.,data=Breamdata)
summary(best.model2)
```

```{r}
anova(fullup,best.model2)
```


# Smelt
## Methods

<!--Decide on your methods:  use "variable analysis" or other appropriate descriptors.  Make sure to choose at least one graphical method and at least one numerical method.!-->

```{r}
Smeltdata=filter(Fishdata,Species=="Smelt")
Smeltdata = subset(Smeltdata, select= -Species)
```

## Inferential Results

<!--State hypothesis clearly.  Make sure your discussion of the inferential test covers all the aspects that the test output produces, such as test statistic, p-value etc.  Make a decision about the null hypothesis, explain the assumptions on which the selected test/procedure was based, and why the chosen procedure satisfys the assumptions and is appropriate to answer the research question!-->

```{r}
library(leaps)
regsubsets.out <-
    regsubsets(Weight~.,
               data = Smeltdata,
               nbest = 1,       # 1 best model for each number of predictors
               nvmax = NULL,    # NULL for no limit on number of variables
               force.in = NULL, force.out = NULL,
               method = "exhaustive")

summary.out <- summary(regsubsets.out)
as.data.frame(summary.out$outmat)
library(car)
subsets(regsubsets.out,statistic="adjr2",legend="bottomright",main="Adjusted R^2")
```
  
##Which is best??  

```{r}
which.max(summary.out$adjr2)
```
```{r}
summary.out$which[3,]
```

```{r}
best.model3 <- lm(Weight~Height+Width,data=Smeltdata)
fullup <- lm(Weight~.,data=Smeltdata)
summary(best.model3)
```

```{r}
anova(fullup,best.model3)
```


# Discussion and Conclusion

<!--Discussion and conclusion here.  If you found a relationship be sure to consider whether the relationship occurs because one of the variavbles causes the other, or whether they perhasps are related for some other reason.  Watch the chapter 6 videos from the GeorgeTown videos collection.!-->


